---
kafka:
   bootstrap-servers: localhost:9092
topics:
   node-tracks: node-tracks
   track-features: track-features
   tracklet-associateds: tracklet-associateds
   global-tracks: global-tracks

jdbc: postgresql:localhost:5432:dna:urc2004:dna
tables:
   node-tracks: node_tracks_index
   track-features: track_features_index
   tracklet-associateds: tracklet-associateds
   associations: associations

motion:
   overlap-area: overlap_areas_h.yaml
   match:
      window-size: 1s
      advance-time: 500ms
      max-distance: 7m

feature:
   camera-network: camera_network_h.yaml
   listening-nodes:
      - etri:05
      - etri:06
   match:
      min-score: 0.3
      top-percent: 0.3
   
output:
   max-association-delay: 3m
   cache-size: 128
   interval: 100ms
   grace-time: 100ms

