---
kafka:
   bootstrap-servers: localhost:9092
   topics:
      node-tracks: node-tracks
      track-features: track-features
      tracklet-associateds: tracklet-associateds
      global-tracks: global-tracks

jdbc: postgresql:localhost:6432:dna:urc2004:dna
tables:
   associations: associations
   node-tracks: node_tracks_index
   track-features: track_features_index
   tracklet-associateds: tracklet-associateds

motion:
   overlap-area: overlap_areas_m.yaml
   match:
      window-size: 1s
      advance-time: 500ms
      max-distance: 8m
   
output:
   max-association-delay: 3m
   cache-size: 128
   interval: 100ms
   grace-time: 100ms