version: "3.1"
name: jarvey-streams

services:
  build_node_tracks_index:
    image: kwlee0220/jarvey.streams:0.1.0
    container_name: build_node_tracks_index
    volumes:
      - ./jarvey:/jarvey
    network_mode: host
    environment:
      JARVEY_STREAMS_HOME: "/jarvey"
      log4j.configurationFile: "/jarvey/log4j2.xml"
    command: java -cp /jarvey.streams.jar jarvey.streams.assoc.tool.BuildNodeTrackIndexMain

  build_track_features_index:
    image: kwlee0220/jarvey.streams:0.1.0
    container_name: build_track_features_index
    volumes:
      - ./jarvey:/jarvey
    network_mode: host
    environment:
      JARVEY_STREAMS_HOME: "/jarvey"
      log4j.configurationFile: "/jarvey/log4j2.xml"
    command: java -cp /jarvey.streams.jar jarvey.streams.assoc.tool.BuildTrackFeatureIndexMain
